In [1]:
import numpy as np
import matplotlib.pyplot as plt
from sklearn import datasets
from sklearn.preprocessing import StandardScaler

from itertools import cycle, islice

In [2]:
plt.rcParams['figure.figsize'] = 12,8

[2 8 4 9 1 6 7 3 0 5]
[2 8 4 9 1 6 7 3 0 5]
[3 5 1 2 9 8 0 6 7 4]
[2 8 4 9 1 6 7 3 0 5]
[0.43758721 0.891773   0.96366276 0.38344152]
[0.79172504 0.52889492 0.56804456 0.92559664]
