In [2]:
import numpy as np

In [3]:
arr1 = np.array([1,2,3,4])
arr1

array([1, 2, 3, 4])

In [4]:
arr2 = np.array([5,6,7,8], dtype=float)
arr2

array([5., 6., 7., 8.])

In [8]:
arr2.dtype

dtype('float64')

In [14]:
arr3 = np.array([[1,2,3],[4,5,6],[7,8,9]])
np.shape(arr3)

(3, 3)

In [15]:
import pandas as pd

In [16]:
df = pd.DataFrame()
type(df)

pandas.core.frame.DataFrame

In [17]:
x = df.values
type(x)

numpy.ndarray

In [18]:
my_series = pd.Series([1,2,3,4,5])
my_series

0    1
1    2
2    3
3    4
4    5
dtype: int64

In [19]:
type(my_series)

pandas.core.series.Series

In [20]:
my_series.values

array([1, 2, 3, 4, 5], dtype=int64)

In [21]:
type(my_series.values)

numpy.ndarray

## Другие способы задания массива

In [23]:
# одномерный массив из пяти элементов, память для которого выделена, но не инициализирована
np.empty(5)

array([1.12427807e-311, 1.12427807e-311, 1.12427807e-311, 1.12427807e-311,
       1.12427807e-311])

In [25]:
# массив размером 10х7, заполненный нулями
np.zeros((10,7))

array([[0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.]])

In [26]:
# массив, размером 3х3х3, заполненный единицами
np.ones((3,3,3))

array([[[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]]])

In [28]:
# единичная матрица (элементы главной диагонали равны 1, остальные 0), размером 3х3
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [30]:
# матрица размером 3х4, заполненная числом 3,14
np.full((3,4), 3.14)

array([[3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14]])

In [32]:
# одномерный массив, заполненный числами от 0 до 30 с шагом 7
np.arange(0,31,7)

array([ 0,  7, 14, 21, 28])

In [36]:
# массив из 5 чисел, равномерно распределенных в интервале от 0 до 1
np.linspace(0,1,5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [37]:
# массив размером 3х3, заполненный случайными числами в интервале от 0 до 9 (включительно)
np.random.randint(0,10,(3,3))

array([[2, 4, 1],
       [0, 1, 8],
       [2, 3, 1]])

In [44]:
my_secret = [x for x in range(1,301,7) if x%10==7 or x%10==1]
np.array([my_secret,[x/2 for x in my_secret],[x-100 for x in my_secret]])

array([[  1. ,  57. ,  71. , 127. , 141. , 197. , 211. , 267. , 281. ],
       [  0.5,  28.5,  35.5,  63.5,  70.5,  98.5, 105.5, 133.5, 140.5],
       [-99. , -43. , -29. ,  27. ,  41. ,  97. , 111. , 167. , 181. ]])

In [53]:
np.array([i for i in range(11) if i%2])

array([1, 3, 5, 7, 9])

In [54]:
my_array = np.array([x for x in range(10)])
my_array

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [55]:
my_array[5]

5

In [56]:
my_array[-1]

9

In [57]:
my_array[3:6]

array([3, 4, 5])

In [58]:
my_array[1:8:3]

array([1, 4, 7])

In [62]:
my_array = np.array([[1,2,3,4], [10,11,12,13], [45,46,47,48]])
my_array

array([[ 1,  2,  3,  4],
       [10, 11, 12, 13],
       [45, 46, 47, 48]])

In [64]:
my_array[1][2]

12

In [65]:
my_array[1,2]

12

In [67]:
my_array[1]

array([10, 11, 12, 13])

In [69]:
my_array[:,2]

array([ 3, 12, 47])

In [70]:
my_array[1:,1:3]

array([[11, 12],
       [46, 47]])

In [94]:
first_line = [x*y for x in range(2,100,6) for y in range(7,1,-2)]
second_line = [x**0.5 for x in range(1000,1101,2)]
third_line = [x**2 for x in range(51)]

big_secret = np.array([first_line, second_line, third_line, second_line, first_line])
big_secret

array([[1.40000000e+01, 1.00000000e+01, 6.00000000e+00, 5.60000000e+01,
        4.00000000e+01, 2.40000000e+01, 9.80000000e+01, 7.00000000e+01,
        4.20000000e+01, 1.40000000e+02, 1.00000000e+02, 6.00000000e+01,
        1.82000000e+02, 1.30000000e+02, 7.80000000e+01, 2.24000000e+02,
        1.60000000e+02, 9.60000000e+01, 2.66000000e+02, 1.90000000e+02,
        1.14000000e+02, 3.08000000e+02, 2.20000000e+02, 1.32000000e+02,
        3.50000000e+02, 2.50000000e+02, 1.50000000e+02, 3.92000000e+02,
        2.80000000e+02, 1.68000000e+02, 4.34000000e+02, 3.10000000e+02,
        1.86000000e+02, 4.76000000e+02, 3.40000000e+02, 2.04000000e+02,
        5.18000000e+02, 3.70000000e+02, 2.22000000e+02, 5.60000000e+02,
        4.00000000e+02, 2.40000000e+02, 6.02000000e+02, 4.30000000e+02,
        2.58000000e+02, 6.44000000e+02, 4.60000000e+02, 2.76000000e+02,
        6.86000000e+02, 4.90000000e+02, 2.94000000e+02],
       [3.16227766e+01, 3.16543836e+01, 3.16859590e+01, 3.17175031e+01,
       

In [72]:
sum(big_secret[:,-1])

3154.332495807108

In [85]:
my_array = big_secret[:,-5:]
#reduce(lambda res,x: res*x, np.diagonal(my_array), 1)
#my_array
def multiply(lst):
    answer = 1
    for i in lst:
        answer *= i
    return answer

multiply(np.diagonal(my_array))


341505315559.2347

In [86]:
np.prod(np.diagonal(my_array))

341505315559.2347

In [88]:
my_array = np.random.randint(1,100,(4,6))
my_array

array([[95, 63, 94,  4, 44, 84],
       [96,  7, 97, 72, 65, 47],
       [93, 73, 34, 40, 18, 71],
       [80, 28, 98, 89, 36, 87]])

In [91]:
my_slice = my_array[1:3, 2:4]
my_slice

array([[97, 72],
       [34, 40]])

In [92]:
my_slice[:] = 0
my_array

array([[95, 63, 94,  4, 44, 84],
       [96,  7,  0,  0, 65, 47],
       [93, 73,  0,  0, 18, 71],
       [80, 28, 98, 89, 36, 87]])

In [96]:
my_slice1 = big_secret[1::2,1::2]
my_slice2 = big_secret[0::2,0::2]
my_slice1[:]=-1
my_slice2[:]=1
big_secret

array([[ 1.00000000e+00,  1.00000000e+01,  1.00000000e+00,
         5.60000000e+01,  1.00000000e+00,  2.40000000e+01,
         1.00000000e+00,  7.00000000e+01,  1.00000000e+00,
         1.40000000e+02,  1.00000000e+00,  6.00000000e+01,
         1.00000000e+00,  1.30000000e+02,  1.00000000e+00,
         2.24000000e+02,  1.00000000e+00,  9.60000000e+01,
         1.00000000e+00,  1.90000000e+02,  1.00000000e+00,
         3.08000000e+02,  1.00000000e+00,  1.32000000e+02,
         1.00000000e+00,  2.50000000e+02,  1.00000000e+00,
         3.92000000e+02,  1.00000000e+00,  1.68000000e+02,
         1.00000000e+00,  3.10000000e+02,  1.00000000e+00,
         4.76000000e+02,  1.00000000e+00,  2.04000000e+02,
         1.00000000e+00,  3.70000000e+02,  1.00000000e+00,
         5.60000000e+02,  1.00000000e+00,  2.40000000e+02,
         1.00000000e+00,  4.30000000e+02,  1.00000000e+00,
         6.44000000e+02,  1.00000000e+00,  2.76000000e+02,
         1.00000000e+00,  4.90000000e+02,  1.00000000e+0

In [102]:
sum(np.diagonal(big_secret[:,0:5]))
#big_secret[:,0:5]

1.0

In [104]:
np.prod(np.diagonal(big_secret[:,-5:]))

1.0