Допустим, у нас есть $n$ товаров с заданными стоимостями $v_i$ и массой $w_i$. В сумку убирается $С$ кг. Сколько какого товара взять, чтобы сумма всех стоимостей товаров была наибольшей?

In [4]:
values = [4, 2, 1, 7, 3, 6]
weights = [5, 9, 8, 2, 6, 5]
C = 15
n = 6

Сформулируем задачу:
$$\max\sum v_i x_i$$
$$\sum w_i x_i \leq C $$

Как должна выглядеть задача:
$$\min c^T x$$
$$A x \leq b $$

Получается, что $c=-v$, $A=w^T$, $b=(C)$

In [5]:
import numpy as np
np.set_printoptions(suppress = True)

In [6]:
c = - np.array(values)
A = np.array(weights)         #shape = (6,)
A = np.expand_dims(A, 0)      #shape = (1,6)
b = np.array([C])

In [16]:
A.shape

(1, 6)

In [7]:
from scipy.optimize import linprog

In [8]:
linprog(c=c, A_ub=A, b_ub=b)

     con: array([], dtype=float64)
     fun: -52.50000000003075
 message: 'Optimization terminated successfully.'
     nit: 5
   slack: array([-0.])
  status: 0
 success: True
       x: array([0. , 0. , 0. , 7.5, 0. , 0. ])

In [9]:
!pip install cvxpy 

  Using cached cvxpy-1.1.17-cp39-cp39-win_amd64.whl (852 kB)
  Using cached scs-2.1.4.tar.gz (6.6 MB)
  Installing build dependencies: started
  Installing build dependencies: finished with status 'done'
  Getting requirements to build wheel: started
  Getting requirements to build wheel: finished with status 'done'
  Preparing metadata (pyproject.toml): started
  Preparing metadata (pyproject.toml): finished with status 'done'
  Using cached osqp-0.6.2.post0-cp39-cp39-win_amd64.whl (162 kB)
  Using cached ecos-2.0.7.post1.tar.gz (126 kB)
  Preparing metadata (setup.py): started
  Preparing metadata (setup.py): finished with status 'done'
  Using cached qdldl-0.1.5.post0-cp39-cp39-win_amd64.whl (74 kB)
Using legacy 'setup.py install' for ecos, since package 'wheel' is not installed.
Failed to build scs


  ERROR: Command errored out with exit status 1:
   command: 'c:\users\user\appdata\local\programs\python\python39\python.exe' 'c:\users\user\appdata\local\programs\python\python39\lib\site-packages\pip\_vendor\pep517\in_process\_in_process.py' build_wheel 'C:\Users\User\AppData\Local\Temp\tmp6zkamk9s'
       cwd: C:\Users\User\AppData\Local\Temp\pip-install-l1yko4x1\scs_a5a363f189024f7d9142add303385a18
  Complete output (82 lines):
  Namespace(scs=False, gpu=False, float32=False, extraverbose=False, gpu_atrans=True, int32=False, blas64=False)
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build\lib.win-amd64-3.9
  creating build\lib.win-amd64-3.9\scs
  copying src\__init__.py -> build\lib.win-amd64-3.9\scs
  running build_ext
  blas_mkl_info:
    NOT AVAILABLE
  blis_info:
    NOT AVAILABLE
  openblas_info:
      library_dirs = ['D:\\a\\1\\s\\numpy\\build\\openblas_info']
      libraries = ['openblas_info']
      language = f77
      define_macros

In [2]:
import cvxpy

In [10]:
x = cvxpy.Variable(shape=n, integer = True)

In [11]:
constraint = (A @ x <= b)
total_value = c * x

c:\users\user\appdata\local\programs\python\python39\lib\site-packages\cvxpy\expressions\expression.py:558: UserWarning: 
This use of ``*`` has resulted in matrix multiplication.
Using ``*`` for matrix multiplication has been deprecated since CVXPY 1.1.
    Use ``*`` for matrix-scalar and vector-scalar multiplication.
    Use ``@`` for matrix-matrix and matrix-vector multiplication.
    Use ``multiply`` for elementwise multiplication.
This code path has been hit 1 times so far.

  warnings.warn(msg, UserWarning)


In [12]:
problem = cvxpy.Problem(cvxpy.Minimize(total_value), constraints=[constraint])

In [13]:
problem.solve()

SolverError: Problem is mixed-integer, but candidate QP/Conic solvers ([]) are not MIP-capable.

In [18]:
x.value

array([ 8388608.00000001, -8388608.00000001, -8388608.00000001,
        8388608.00000001,  6990509.00000001,  8388608.00000001])

Теперь положительные $x$

In [14]:
x = cvxpy.Variable(shape=n, integer=True)
constraint = (A @ x <= b)
x_positive = (x >= 0)
total_value = c * x
problem = cvxpy.Problem(cvxpy.Minimize(total_value), constraints=[constraint, x_positive])
problem.solve()

c:\users\user\appdata\local\programs\python\python39\lib\site-packages\cvxpy\expressions\expression.py:558: UserWarning: 
This use of ``*`` has resulted in matrix multiplication.
Using ``*`` for matrix multiplication has been deprecated since CVXPY 1.1.
    Use ``*`` for matrix-scalar and vector-scalar multiplication.
    Use ``@`` for matrix-matrix and matrix-vector multiplication.
    Use ``multiply`` for elementwise multiplication.
This code path has been hit 2 times so far.

  warnings.warn(msg, UserWarning)


SolverError: Problem is mixed-integer, but candidate QP/Conic solvers ([]) are not MIP-capable.

In [20]:
x.value

array([7.01265807e-10, 7.99333027e-10, 3.58703130e-10, 7.00000000e+00,
       4.67143021e-10, 9.34955115e-10])

Теперь $x = 0$ или $1$

In [21]:
x = cvxpy.Variable(shape=n, boolean=True)
constraint = A @ x <= b
x_positive = x >= 0
total_value = c * x
problem = cvxpy.Problem(cvxpy.Minimize(total_value), constraints=[constraint, x_positive])
problem.solve()

-17.00000000382157

In [22]:
x.value

array([1.00000000e+00, 2.25474413e-10, 2.07396078e-10, 1.00000000e+00,
       2.24003299e-10, 1.00000000e+00])

In [1]:
import numpy as np
np.set_printoptions(suppress=True)
from scipy.optimize import linprog

In [3]:
c = np.array([2,5,3,7,7,6]) #costs
A_ub = np.array([[1,1,1,0,0,0],
                [0,0,0,1,1,1]])
b_ub = np.array([180,220]) #rests
A_eq = np.array([[1,0,0,1,0,0],
                [0,1,0,0,1,0],
                [0,0,1,0,0,1]])
b_eq = np.array([110,150,140]) #needs

In [4]:
linprog(c=c, A_ub=A_ub, b_ub=b_ub, A_eq=A_eq, b_eq=b_eq)

     con: array([0.00000439, 0.00000602, 0.00000561])
     fun: 1899.9999256826582
 message: 'Optimization terminated successfully.'
     nit: 5
   slack: array([0.0000072 , 0.00000882])
  status: 0
 success: True
       x: array([109.99999471,   0.00000004,  69.99999804,   0.0000009 ,
       149.99999394,  69.99999634])