In [26]:
import numpy as np
import pandas as pd
import math

In [3]:
s_common = np.array([33,42,33,65])
s_living = np.array([24,32,20,48])
p = s_common + s_living/4
p

array([39., 50., 38., 77.])

In [8]:
p_real = np.array([40,48.46,39,77])
n = p_real-p
n

array([ 1.  , -1.54,  1.  ,  0.  ])

In [16]:
np.dot(s_common,s_common)

8167

In [17]:
s_common@s_common

8167

In [18]:
math.sqrt(s_common@s_common)

90.37145567047152

In [19]:
np.linalg.norm(s_common)

90.37145567047152

In [21]:
# Нормировка вектора
a = np.array([1,2,3])
np.linalg.norm(a)

3.7416573867739413

In [24]:
a_norm = a/np.linalg.norm(a)
print('a: ', a)
print('a_norm: ', a_norm)
print('length of a_norm: ', np.linalg.norm(a_norm))

a:  [1 2 3]
a_norm:  [0.26726124 0.53452248 0.80178373]
length of a_norm:  1.0


In [27]:
df = pd.DataFrame({'1.Rent': [65, 70, 120, 35, 40, 50, 100, 90, 85], 
                                '2.Area': [50, 52, 80, 33, 33, 44, 80, 65, 65], 
                                '3.Rooms':[3, 2, 1, 1, 1, 2, 4, 3, 2],
                                '4.Floor':[5, 12, 10, 3, 6, 13, 8, 21, 5], 
                                '5.Demo two weeks':[8, 4, 5, 10, 20, 12, 5, 1, 10], 
                                '6.Liv.Area': [37, 40, 65, 20, 16, 35, 60, 50, 40]})
display(df)

1.Rent  2.Area  3.Rooms  4.Floor  5.Demo two weeks  6.Liv.Area
0      65      50        3        5                 8          37
1      70      52        2       12                 4          40
2     120      80        1       10                 5          65
3      35      33        1        3                10          20
4      40      33        1        6                20          16
5      50      44        2       13                12          35
6     100      80        4        8                 5          60
7      90      65        3       21                 1          50
8      85      65        2        5                10          40

In [30]:
df.values[4]

array([40, 33,  1,  6, 20, 16], dtype=int64)

In [39]:
df.values[:,1]-df.values[:,5]

array([13, 12, 15, 13, 17,  9, 20, 15, 25], dtype=int64)

In [40]:
df.values[:,0]*0.4

array([26., 28., 48., 14., 16., 20., 40., 36., 34.])

In [41]:
s = np.array([10,20,30,15,5,40,20,8,20])

In [44]:
df['time'] = s.T
df

1.Rent  2.Area  3.Rooms  4.Floor  5.Demo two weeks  6.Liv.Area  time
0      65      50        3        5                 8          37    10
1      70      52        2       12                 4          40    20
2     120      80        1       10                 5          65    30
3      35      33        1        3                10          20    15
4      40      33        1        6                20          16     5
5      50      44        2       13                12          35    40
6     100      80        4        8                 5          60    20
7      90      65        3       21                 1          50     8
8      85      65        2        5                10          40    20

In [45]:
df.values[:,4]@df.values[:,6]

1348

In [46]:
u=np.array([3,0,1,1,1])
v=np.array([0,1,0,2,-2])
w=np.array([1,-4,-1,0,-2])

In [47]:
print('u@v: ',u@v)
print('u@w: ',u@w)
print('v@w: ',v@w)

u@v:  0
u@w:  0
v@w:  0


In [49]:
(2*v-3*w)@u

0

In [50]:
def norm_vector(s):
    return s/np.linalg.norm(s)

In [51]:
u_norm = norm_vector(u)
v_norm = norm_vector(v)
w_norm = norm_vector(w)

In [54]:
print('u_norm: ', u_norm)
print('v_norm: ', v_norm)
print('w_norm: ', w_norm)

u_norm:  [0.8660254  0.         0.28867513 0.28867513 0.28867513]
v_norm:  [ 0.          0.33333333  0.          0.66666667 -0.66666667]
w_norm:  [ 0.21320072 -0.85280287 -0.21320072  0.         -0.42640143]


In [56]:
print(round(u_norm[2],3),round(v_norm[3],3),round(w_norm[0],3))

0.289 0.667 0.213
